name: 'Paragraph Push Runner'
description: 'Pushes updated code from github branch and sync with paragon project'
inputs:
  paragonKey:
    type: string
    required: true
  npmToken:
    type: string
    required: true
  paragonZeusUrl:
    type: string
    required: true
  paragonDashboardUrl:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate Paragon Git-sync Connection
      id: validateGitSync
      env:
        PARAGON_CLI_KEY: ${{ inputs.paragonKey }}
        PARAGON_HOST_ZEUS: ${{ inputs.paragonZeusUrl }}
        COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
      shell: bash
      run: |
        request_output=$(curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $PARAGON_CLI_KEY" \
          -d "{ \"branchName\": \"${{ github.ref_name }}\", \"author\": \"$COMMIT_AUTHOR\", \"runId\": \"${{ github.run_id }}\", \"hash\": \"${{ github.sha }}\"  }" \
          $PARAGON_HOST_ZEUS/graphite/projects/commit)

        commitId=$(echo "$request_output" | jq -r '.commitId')
        projectId=$(echo "$request_output" | jq -r '.projectId')
        subfolder=$(echo "$request_output" | jq -r '.subfolder')

        echo "commitId=$commitId"   >> $GITHUB_OUTPUT
        echo "projectId=$projectId" >> $GITHUB_OUTPUT
        echo "subfolder=$subfolder" >> $GITHUB_OUTPUT

    - name: Validate Dependency
      id: validate
      shell: bash
      run: |
        if [ "${{ steps.validateGitSync.outputs.projectId }}" = "null" ]; then
          echo "projectId is not provided."
          exit 1
        fi
          
        if [ "${{ steps.validateGitSync.outputs.commitId }}" = "null" ]; then
          echo "commitId is not provided."
          exit 1
        fi 

        if [ -z "${{ inputs.paragonKey }}" ]; then
          echo "paragonKey is not provided."
          exit 1
        fi 

        if [ -z "${{ inputs.npmToken }}" ]; then
          echo "npmToken is not provided."
          exit 1
        fi 

        if [ -z "${{ inputs.paragonZeusUrl }}" ]; then
          echo "paragonZeusUrl is not provided."
          exit 1
        fi 

        if [ -z "${{ inputs.paragonDashboardUrl }}" ]; then
          echo "paragonDashboardUrl is not provided."
          exit 1
        fi

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      with:
        node-version: v18.17.1

    - name: Install para CLI
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npmToken }}" > ~/.npmrc
        npm install -g @useparagon/cli@next

    - name: Authenticate into CLI
      env:
        PARAGON_CLI_KEY: ${{ inputs.paragonKey }}
        PARAGON_HOST_DASHBOARD: ${{ inputs.paragonDashboardUrl }}
        PARAGON_HOST_ZEUS: ${{ inputs.paragonZeusUrl }}
      shell: bash
      run: |
        mkdir -p ~/.paragon
        cat << EOF > ~/.paragon/credentials.json
        {
          "default": {
            "profile": "default",
            "token": "$PARAGON_CLI_KEY"
          }
        }
        EOF
        cat << EOF > ~/.paragon/profiles.json
        {
          "default": {
            "name": "default",
            "default": true,
            "services": {
              "zeus": "$PARAGON_HOST_ZEUS",
              "dashboard": "$PARAGON_HOST_DASHBOARD"
            }
          }
        }
        EOF

    - name: Build Paragraph project
      shell: bash
      run: |
        para install
        para build

    - name: Push to Paragon
      shell: bash
      if: github.event_name == 'push'
      run: para push

    # Post steps
    - name: Update success status in Paragon
      shell: bash
      env:
        PARAGON_CLI_KEY: ${{ inputs.paragonKey }}
        PARAGON_HOST_ZEUS: ${{ inputs.paragonZeusUrl }}
        PROJECT_ID: ${{ steps.validateGitSync.outputs.projectId }}
        COMMIT_ID: ${{ steps.validateGitSync.outputs.commitId }}
      if: ${{ success() }}
      run: |
        echo "Commit succeeded!"
        curl -X PATCH \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $PARAGON_CLI_KEY" \
          -d "{ \"projectId\": \"$PROJECT_ID\", \"commitId\": \"$COMMIT_ID\", \"runId\": \"${{ github.run_id }}\", \"success\": true, \"hash\": \"${{ github.sha }}\"  }" \
          $PARAGON_HOST_ZEUS/graphite/projects/commit

    - name: Update failed status in Paragon
      shell: bash
      env:
        PARAGON_CLI_KEY: ${{ inputs.paragonKey }}
        PARAGON_HOST_ZEUS: ${{ inputs.paragonZeusUrl }}
        PROJECT_ID: ${{ steps.validateGitSync.outputs.projectId }}
        COMMIT_ID: ${{ steps.validateGitSync.outputs.commitId }}
      if: ${{ failure() }}
      run: |
        echo "Commit failed!"
        curl -X PATCH \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $PARAGON_CLI_KEY" \
          -d "{ \"projectId\": \"$PROJECT_ID\", \"commitId\": \"$COMMIT_ID\", \"runId\": \"${{ github.run_id }}\", \"success\": false }" \
          $PARAGON_HOST_ZEUS/graphite/projects/commit
